controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    gripper_controller:
      type: position_controllers/GripperActionController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gripper_controller:
  ros__parameters:
    joints:
      - robotiq_85_left_knuckle_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity